Repository typescript-kr/typescript-kr.github.io, pull requests merged in 2020-05, with the labels that each got.

#47 번역 규칙 및 번역 용어를 기여 방법과 통합
  CONTRIBUTING.md
Labels: 프로젝트

#60 동작하지 않는 anchor 수정
  pages/Advanced Types.md
Labels: 오타 및 잘못된 번역

#61 templates 파일 추가
  SUMMARY.md
Labels: 오타 및 잘못된 번역

#62 Module Resolution.md 오타 수정
  pages/Module Resolution.md
Labels: 오타 및 잘못된 번역

#65 typescript-in-5-minutes 다운로드 안내 링크 수정
  pages/tutorials/TypeScript in 5 minutes.md
Labels: 오타 및 잘못된 번역

#63 tsconfig.json.md 번역 및 검토 완료 (fix #50)
  pages/tsconfig.json.md
Labels: 번역중

#64 compiler options 전체 검토 및 번역 (ref #51)
  pages/Compiler Options.md
Labels: 번역중

#66 TypeScript 3.9 release note 추가
  .markdownlint.json
  pages/release notes/TypeScript 3.9.md
Labels: 프로젝트

#68 Intergrating with Build Tools 전체 검토 및 번역 (ref #54)
  pages/Integrating with Build Tools.md
Labels: 번역중

#74 3.9 릴리즈 노트 editor improvements 번역
  pages/release notes/TypeScript 3.9.md
Labels: 번역중

#75 TypeScript 3.9.md dvlprsh 부분 번역 (resolve #69)
  pages/release notes/TypeScript 3.9.md
Labels: 번역중

#73 TypeScript 3.9.md bumkeyy 부분 번역 (resolve #70)
  pages/release notes/TypeScript 3.9.md
Labels: 번역중

#76 ts 3.9 breaking changes 번역 (resolve #72)
  pages/release notes/TypeScript 3.9.md
Labels: 번역중
